"""添加关注者显示温江的联结表查询m，自己关注自己的静态方法

Revision ID: 13ee66d1e850
Revises: b3a1a251c65a
Create Date: 2016-08-17 22:40:56.872933

"""

# revision identifiers, used by Alembic.
revision = '13ee66d1e850'
down_revision = 'b3a1a251c65a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
