"""添加关注者显示文章的联结表查询，自己关注自己的静态方法

Revision ID: 4f9c0519eb75
Revises: 89c894f894f2
Create Date: 2016-08-17 23:06:03.795302

"""

# revision identifiers, used by Alembic.
revision = '4f9c0519eb75'
down_revision = '89c894f894f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
