"""add Role

Revision ID: 57921058e3d9
Revises: de7ad7dd2117
Create Date: 2016-08-09 16:34:01.454901

"""

# revision identifiers, used by Alembic.
revision = '57921058e3d9'
down_revision = 'de7ad7dd2117'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
