"""更新

Revision ID: 626b1c24fd28
Revises: 755a2f946569
Create Date: 2016-08-11 22:15:00.093697

"""

# revision identifiers, used by Alembic.
revision = '626b1c24fd28'
down_revision = '755a2f946569'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
