"""add user_Information

Revision ID: 68d1fd4af098
Revises: 199f95b3a2ea
Create Date: 2016-08-09 17:11:13.163608

"""

# revision identifiers, used by Alembic.
revision = '68d1fd4af098'
down_revision = '199f95b3a2ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
