"""添加关注者显示温江的联结表查询m，自己关注自己的静态方法

Revision ID: 89c894f894f2
Revises: 13ee66d1e850
Create Date: 2016-08-17 23:05:19.346899

"""

# revision identifiers, used by Alembic.
revision = '89c894f894f2'
down_revision = '13ee66d1e850'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
