"""增加处理服务器中预处理markdown

Revision ID: db6148ee62c9
Revises: 626b1c24fd28
Create Date: 2016-08-15 16:39:29.618645

"""

# revision identifiers, used by Alembic.
revision = 'db6148ee62c9'
down_revision = '626b1c24fd28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
