"""initial migration

Revision ID: de7ad7dd2117
Revises: 03d3971f4316
Create Date: 2016-08-08 21:02:46.178761

"""

# revision identifiers, used by Alembic.
revision = 'de7ad7dd2117'
down_revision = '03d3971f4316'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
