"""更改用户，增加头像

Revision ID: f8aa1a7aa243
Revises: 68d1fd4af098
Create Date: 2016-08-10 19:55:00.700994

"""

# revision identifiers, used by Alembic.
revision = 'f8aa1a7aa243'
down_revision = '68d1fd4af098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
