"""增加处理服务器中预处理markdown(副本)

Revision ID: fdb2c1a27110
Revises: db6148ee62c9
Create Date: 2016-08-15 16:46:26.764529

"""

# revision identifiers, used by Alembic.
revision = 'fdb2c1a27110'
down_revision = 'db6148ee62c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
